package org.objectstyle.graphql.it.fixture.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.objectstyle.graphql.it.fixture.cayenne.E2;

/**
 * Class _E1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E1 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<E2>> E2S = new Property<List<E2>>("e2s");

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE2s(E2 obj) {
        addToManyTarget("e2s", obj, true);
    }
    public void removeFromE2s(E2 obj) {
        removeToManyTarget("e2s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E2> getE2s() {
        return (List<E2>)readProperty("e2s");
    }


}
