package org.objectstyle.graphql.it.fixture.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.objectstyle.graphql.it.fixture.cayenne.E1;
import org.objectstyle.graphql.it.fixture.cayenne.E3;

/**
 * Class _E2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E2 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> E1_ID = new Property<Integer>("e1_id");
    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<E1> E1 = new Property<E1>("e1");
    public static final Property<List<E3>> E3S = new Property<List<E3>>("e3s");

    public void setE1_id(Integer e1_id) {
        writeProperty("e1_id", e1_id);
    }
    public Integer getE1_id() {
        return (Integer)readProperty("e1_id");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setE1(E1 e1) {
        setToOneTarget("e1", e1, true);
    }

    public E1 getE1() {
        return (E1)readProperty("e1");
    }


    public void addToE3s(E3 obj) {
        addToManyTarget("e3s", obj, true);
    }
    public void removeFromE3s(E3 obj) {
        removeToManyTarget("e3s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E3> getE3s() {
        return (List<E3>)readProperty("e3s");
    }


}
